[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "always"

[[services]]
name = "backend"
source = "server"

[services.build]
buildCommand = "npm run build"

[services.deploy]
startCommand = "npm run start:prod"